SET SERVEROUTPUT ON;

DECLARE
 V_TEXT VARCHAR2 (50) NOT NULL DEFAULT 'HELLO';
BEGIN
 V_TEXT := 'PL/SQL' || ' COURSE';
 DBMS_OUTPUT.PUT_LINE(V_TEXT);
END;

DECLARE
 V_TEXT VARCHAR2 (50) NOT NULL := 'WELCOME';
BEGIN
 DBMS_OUTPUT.PUT_LINE(V_TEXT || ' BEGINNER TO ADVANCED');
END;

DECLARE
 V_NUMBER NUMBER(4,2) NOT NULL := 50.42;
BEGIN
 DBMS_OUTPUT.PUT_LINE(V_NUMBER);
END;

DECLARE
 V_NUMBER PLS_INTEGER NOT NULL := 50;
BEGIN
 DBMS_OUTPUT.PUT_LINE(V_NUMBER);
END;

DECLARE
 V_NUMBER BINARY_INTEGER NOT NULL := 50;
BEGIN
 DBMS_OUTPUT.PUT_LINE(V_NUMBER);
END;

DECLARE
 V_NUMBER BINARY_FLOAT NOT NULL := 50.42f;
BEGIN
 DBMS_OUTPUT.PUT_LINE(V_NUMBER);
END;

DECLARE
 V_DATE DATE NOT NULL := SYSDATE;
BEGIN
 DBMS_OUTPUT.PUT_LINE(V_DATE);
END;

DECLARE
 V_DATE TIMESTAMP(3) WITH TIME ZONE NOT NULL := SYSTIMESTAMP;
BEGIN
 DBMS_OUTPUT.PUT_LINE(V_DATE);
END;

DECLARE
 V_DATE INTERVAL DAY(4) TO SECOND(2) := '24 02:05:21.012';
BEGIN
 DBMS_OUTPUT.PUT_LINE(V_DATE);
END;

DECLARE
 V_DATE INTERVAL YEAR(3) TO MONTH := '122-3';
BEGIN
 DBMS_OUTPUT.PUT_LINE(V_DATE);
END